### PR TITLE
Schedule Deneb on Chiado

### PR DESCRIPTION
**Pull request by dapplion**
EU friendly time after Ethereum's Goerli fork.

```
Slot 8265728 ts 1706724940 UTC Wed 31/01/2024, 18:15:40
```

### CODE REVIEW

**Review by filoozom — APPROVED** [review]
The time is also right after Sepolia, as we wanted to hard fork around the middle of the 3 testnet hard forks. This way we know if anything wrong happened with Goerli and stay in schedule with Ethereum.

**Comment by zilm13** [comment]
Hello, clients may need more info for implementation.

Following constants should be the part of config too, could you clarify it's the same as in gnosis (or better add to this config too):
```
# Deneb
# `2**7` (=128)
MAX_REQUEST_BLOCKS_DENEB: 128
# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK
MAX_REQUEST_BLOB_SIDECARS: 768
# `2**14` (= 16384 epochs, ~15 days)
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 16384
# `6`
BLOB_SIDECAR_SUBNET_COUNT: 6
```
Also I cannot find gnosis deneb preset which should contain `MAX_BLOBS_PER_BLOCK`, `FIELD_ELEMENTS_PER_BLOB`, `MAX_BLOB_COMMITMENTS_PER_BLOCK`, `KZG_COMMITMENT_INCLUSION_PROOF_DEPTH`.

The last piece of puzzle is trusted setup, which one will be used?

Also `16384*16*6*128kb = 200Gb`, where does estimate of 35Gb come from?

**Comment by filoozom** [comment]
@zilm13 you can find the preset, and more specifically the deneb one here: https://github.com/gnosischain/specs/blob/master/consensus/preset/gnosis/deneb.yaml.

The configuration for Chiado hasn't been specified yet, but all configuration variables will be the same as for Ethereum. The full file will be made available shortly.

Regarding the size estimate, while on the CL side `MAX_BLOBS_PER_BLOCK` is indeed set to `6` to maintain compatibility with Ethereum, it will actually be limited to `2` on the EL. The target is also set to `1`, So we end up with:

```
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS * SLOTS_PER_EPOCH * TARGET_BLOBS_PER_BLOCK * BYTES_PER_FIELD_ELEMENT * FIELD_ELEMENTS_PER_BLOB = 4096 * 16 * 1 * 32 * 4096 = 8.6GB
```

I'm not sure where the discrepancy comes from, maybe I missed something in my formula, I'll check tomorrow. What variables do the numbers in your calculation represent?

**Comment by zilm13** [comment]
With target 1 it could be estimated as 35G (200G/6), right.
What about trusted setup, which one should be used?

**Comment by zilm13** [comment]
Btw documentation on https://docs.gnosischain.com/about/networks/chiado leads to https://github.com/gnosischain/configs/ where there are no presets, that's why I asked for presets

**Comment by filoozom** [comment]
First, thank you for opening the issue on Teku's GitHub. Don't worry though, we'll open PRs on all CL clients in due time. To answer your questions:

> With target 1 it could be estimated as 35G (200G/6), right.

I'm not exactly sure where the 200 GB estimation comes from, and I'm not sure if the size is dependent on the target or the maximum. Assuming the worst case and that the formula above is right, I get `4096 * 32 * 6 * 32 * 4096 = 103.07 GB` for Ethereum.

For Gnosis Chain, we only have 16 slots per epoch and a target of 2, so effectively 6x less required space in the worst case, which is 17.2 GB, or double of my earlier approximation with the target rather than the maximal amount. However, the bandwidth requirements would be closer to Ethereum, as that data would be "refreshed" on a more regular basis.

@dapplion it would be nice if you could confirm those numbers.

> What about trusted setup, which one should be used?

The same one as Ethereum to stay as compatible as possible.

**Comment by dapplion** [comment]
- Trusted setup added in https://github.com/gnosischain/specs/pull/30

**Comment by zilm13** [comment]
@filoozom 
mainnet has `MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS` 4096, while gnosis [16384](https://github.com/gnosischain/specs/blob/master/consensus/config/gnosis.yaml#L133-L134). Though epochs are twice smaller (16 slots vs 32), requirement for epochs is 4x. So you need to keep 2x blobs comparing to mainnet (worst cases compared)

**Comment by filoozom** [comment]
You're totally right, `MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS` is still missing from the Chiado config (which we're going to update soon), and I apparently forgot about the change, so I assumed that we were using the `4096` value from Ethereum mainnet, which we aren't.

So 4x more min epochs, 2x less slots per epoch and 3x less target / max blobs per block. So 2/3 of Ethereum, meaning 34.4 GB target and 68.7 GB max. Not sure which one actually ends up being required.

**Comment by dapplion** [comment]
- Chiado config values updated in https://github.com/gnosischain/configs/pull/27

**Pull request merged**
